name: Docker Image CI

on:
  push:
    tags: [ '*.*.*' ]
    paths: [ 'Dockerfile' ]
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ github.ref_type == 'tag' }}
        id: docker_build_tag
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: |
            sdvcrx/hugo-firebase:${{ github.ref_name }}
            ghcr.io/sdvcrx/hugo-firebase:${{ github.ref_name }}
          platforms: linux/amd64

      - name: Build and push latest
        if: ${{ github.ref_type == 'branch' }}
        id: docker_build_latest
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: |
            sdvcrx/hugo-firebase:latest
            ghcr.io/sdvcrx/hugo-firebase:latest
          platforms: linux/amd64
